apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dynatrace-default-view
subjects:
- kind: ServiceAccount
  name: default
  namespace: dynatrace
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io 