apiVersion: v1
kind: Service
metadata:
  name: dynatrace-otel-collector
  namespace: default
spec:
  selector:
    app: otel-collector
  ports:
    # Port 4317 for OTLP gRPC (used by applications)
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    # Port 4318 for OTLP HTTP (used by applications)
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: 4318
  type: ClusterIP